### PR TITLE
irpmonc: Print help text on --help and hint about it on wrong usage

### PR DESCRIPTION
**Pull request by tormodvolden**

### CODE REVIEW

**Comment by tormodvolden** [comment]
I had first used the text in the comments as-is without looking too much at it. The second commit changes the indentation to make it more consistent. The two commits can be squashed, let me know.

**Comment by tormodvolden** [comment]
I squashed, rebased to master and added a missing newline on the first line.

**Comment by MartinDrab** [comment]
> I squashed, rebased to master and added a missing newline on the first line.

In general, there is no need to rebase unless there are conflicts.

Thank you very much for your effort! Appreciated!

**Comment by tormodvolden** [comment]
Well, I rebase locally anyway (and I need several of these branches together in order to compile and test here), and it is a way to see if there would be any conflicts and not leave those to the maintainer.

**Comment by tormodvolden** [comment]
After you get to merge this, would it be possible to have another RC (or snapshot release) with new binaries in a not too distant future?

**Comment by MartinDrab** [comment]
> After you get to merge this, would it be possible to have another RC (or snapshot release) with new binaries in a not too distant future?

I suppose I can do this during this weekend. The only problem (but possibly not for you) is that I currently am unable to sign the drivers with a trusted cert. Thus, if someone would like to load them, he/she needs to disable Secure Boot, enable test signing, and add the test cert into Trusted Root Certificate Authorities.

**Comment by tormodvolden** [comment]
Great. Yes, the unsigned driver is a bit annoying. An alternative to using the test cert is to select “Disable Driver Signature Enforcement” in the advanced  startup menu, it seems disabling Secure boot is then not needed. Funnily I had it working doing this for a while, but now I cannot get it to work again, even when disabling Secure boot. That's when I started to use irpmonc.exe instead of the GUI in hope of having more debug information but soon discovered a things that could need fixing.

**Pull request merged**
